// Mock data for development and testing
import { Product, RecoConfig } from '@shared/schema';

export const mockProducts: Product[] = [
  {
    id: 'prod-1',
    store_id: 'dev-store-1',
    external_id: 'shopify-123',
    title: 'Wireless Bluetooth Headphones',
    description: 'Premium noise-cancelling wireless headphones with 30-hour battery life',
    price: 129.99,
    image_url: 'https://cdn.shopify.com/s/files/1/0533/2089/files/placeholder-images-product-1_large.png',
    vendor: 'AudioTech',
    product_type: 'Electronics',
    tags: ['electronics', 'audio', 'wireless'],
    variants_count: 3,
    inventory_quantity: 45,
  },
  {
    id: 'prod-2',
    store_id: 'dev-store-1',
    external_id: 'shopify-124',
    title: 'Portable Phone Charger 20000mAh',
    description: 'High-capacity power bank with fast charging',
    price: 39.99,
    image_url: 'https://cdn.shopify.com/s/files/1/0533/2089/files/placeholder-images-product-2_large.png',
    vendor: 'PowerPlus',
    product_type: 'Electronics',
    tags: ['electronics', 'charging', 'portable'],
    variants_count: 2,
    inventory_quantity: 120,
  },
  {
    id: 'prod-3',
    store_id: 'dev-store-1',
    external_id: 'shopify-125',
    title: 'Smart Watch Fitness Tracker',
    description: 'Track your fitness goals with heart rate monitoring and GPS',
    price: 199.99,
    image_url: 'https://cdn.shopify.com/s/files/1/0533/2089/files/placeholder-images-product-3_large.png',
    vendor: 'FitTech',
    product_type: 'Wearables',
    tags: ['fitness', 'wearables', 'smart'],
    variants_count: 4,
    inventory_quantity: 67,
  },
  {
    id: 'prod-4',
    store_id: 'dev-store-1',
    external_id: 'shopify-126',
    title: 'USB-C Cable 6ft Braided',
    description: 'Durable braided USB-C charging cable',
    price: 14.99,
    image_url: 'https://cdn.shopify.com/s/files/1/0533/2089/files/placeholder-images-product-4_large.png',
    vendor: 'CableCo',
    product_type: 'Accessories',
    tags: ['accessories', 'cables', 'charging'],
    variants_count: 2,
    inventory_quantity: 230,
  },
  {
    id: 'prod-5',
    store_id: 'dev-store-1',
    external_id: 'shopify-127',
    title: 'Laptop Stand Aluminum',
    description: 'Ergonomic adjustable laptop stand for better posture',
    price: 49.99,
    image_url: 'https://cdn.shopify.com/s/files/1/0533/2089/files/placeholder-images-product-5_large.png',
    vendor: 'DeskMate',
    product_type: 'Accessories',
    tags: ['accessories', 'desk', 'ergonomic'],
    variants_count: 1,
    inventory_quantity: 88,
  },
];

export const mockRecoConfigs: RecoConfig[] = [
  {
    id: 'config-1',
    store_id: 'dev-store-1',
    name: 'Similar Products on PDP',
    recommendation_type: 'similar',
    placement: 'product_page',
    is_enabled: true,
    ai_config: {
      algorithm: 'hybrid',
      confidence_threshold: 0.75,
      max_results: 8,
      diversity_factor: 0.6,
      personalization_weight: 0.7,
      recency_weight: 0.3,
    },
    merchandising_rules: [
      {
        id: 'rule-1',
        type: 'boost',
        product_ids: ['prod-1', 'prod-2'],
        priority: 1,
        is_global: false,
      },
    ],
    manual_product_ids: [],
  },
  {
    id: 'config-2',
    store_id: 'dev-store-1',
    name: 'Frequently Bought Together',
    recommendation_type: 'bought_together',
    placement: 'cart_page',
    is_enabled: true,
    ai_config: {
      algorithm: 'collaborative_filtering',
      confidence_threshold: 0.8,
      max_results: 6,
      diversity_factor: 0.4,
      personalization_weight: 0.8,
      recency_weight: 0.2,
    },
    merchandising_rules: [],
    manual_product_ids: [],
  },
  {
    id: 'config-3',
    store_id: 'dev-store-1',
    name: 'Homepage Trending',
    recommendation_type: 'trending',
    placement: 'home_page',
    is_enabled: false,
    ai_config: {
      algorithm: 'popularity_based',
      confidence_threshold: 0.6,
      max_results: 12,
      diversity_factor: 0.7,
      personalization_weight: 0.5,
      recency_weight: 0.8,
    },
    merchandising_rules: [],
    manual_product_ids: [],
  },
];
